# Generated by Django 2.2 on 2020-08-02 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200802_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Vendor'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='trip_type',
            field=models.CharField(choices=[('outstation', 'outstation')], max_length=120),
        ),
    ]
