# Generated by Django 2.2 on 2020-08-02 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200802_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Vendor'),
        ),
    ]
